# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'canale_view.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_facewindow(object):
    def setupUi(self, facewindow):
        facewindow.setObjectName("facewindow")
        facewindow.resize(1230, 568)
        facewindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../git/SiMPlE/smfsmanager/D_mica.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        facewindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(facewindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.grafo = PlotWidget(self.layoutWidget)
        self.grafo.setMinimumSize(QtCore.QSize(600, 0))
        self.grafo.setToolTip("")
        self.grafo.setStatusTip("")
        self.grafo.setWhatsThis("")
        self.grafo.setObjectName("grafo")
        self.verticalLayout_2.addWidget(self.grafo)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_deriv = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_deriv.setObjectName("radio_deriv")
        self.horizontalLayout.addWidget(self.radio_deriv)
        self.radio_view = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_view.setChecked(True)
        self.radio_view.setObjectName("radio_view")
        self.horizontalLayout.addWidget(self.radio_view)
        self.radio_smooth = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_smooth.setObjectName("radio_smooth")
        self.horizontalLayout.addWidget(self.radio_smooth)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labDetails = QtWidgets.QLabel(self.layoutWidget)
        self.labDetails.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labDetails.setObjectName("labDetails")
        self.horizontalLayout_3.addWidget(self.labDetails)
        self.labFilename = QtWidgets.QLabel(self.layoutWidget)
        self.labFilename.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labFilename.setObjectName("labFilename")
        self.horizontalLayout_3.addWidget(self.labFilename)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_3 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.splitter_3)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.s_mth = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.s_mth.setFont(font)
        self.s_mth.setStyleSheet("border: none;")
        self.s_mth.setDecimals(3)
        self.s_mth.setMaximum(1000.0)
        self.s_mth.setSingleStep(0.1)
        self.s_mth.setProperty("value", 3.0)
        self.s_mth.setObjectName("s_mth")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s_mth)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.s_vth = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.s_vth.setFont(font)
        self.s_vth.setStyleSheet("border: none;")
        self.s_vth.setMaximum(9999.0)
        self.s_vth.setSingleStep(0.1)
        self.s_vth.setProperty("value", 10.0)
        self.s_vth.setObjectName("s_vth")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.s_vth)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: none;")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sg_fw = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.sg_fw.setFont(font)
        self.sg_fw.setStyleSheet("border: none;")
        self.sg_fw.setMinimum(0.01)
        self.sg_fw.setMaximum(99.99)
        self.sg_fw.setSingleStep(0.1)
        self.sg_fw.setProperty("value", 1.0)
        self.sg_fw.setObjectName("sg_fw")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sg_fw)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: none;")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.sg_mm = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.sg_mm.setFont(font)
        self.sg_mm.setStyleSheet("border: none;")
        self.sg_mm.setMinimum(0)
        self.sg_mm.setMaximum(90)
        self.sg_mm.setProperty("value", 10)
        self.sg_mm.setObjectName("sg_mm")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sg_mm)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: none;")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setLineWidth(1)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.plath = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.plath.setFont(font)
        self.plath.setMinimum(-100000.0)
        self.plath.setMaximum(100000.0)
        self.plath.setProperty("value", 30.0)
        self.plath.setObjectName("plath")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.plath)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: none;")
        self.label_6.setLineWidth(1)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lasth = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lasth.setFont(font)
        self.lasth.setMaximum(1000.0)
        self.lasth.setProperty("value", 5.0)
        self.lasth.setObjectName("lasth")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lasth)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: none;")
        self.label_7.setLineWidth(1)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.derorder = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.derorder.setMaximum(10)
        self.derorder.setProperty("value", 1)
        self.derorder.setObjectName("derorder")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.derorder)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cscope = QtWidgets.QPushButton(self.formLayoutWidget)
        self.cscope.setCheckable(True)
        self.cscope.setChecked(False)
        self.cscope.setObjectName("cscope")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cscope)
        self.pjlist = QtWidgets.QListWidget(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.pjlist.setFont(font)
        self.pjlist.setStyleSheet("")
        self.pjlist.setObjectName("pjlist")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.splitter_3)
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.sslabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.sslabel.setFont(font)
        self.sslabel.setStyleSheet("border: none;")
        self.sslabel.setTextFormat(QtCore.Qt.AutoText)
        self.sslabel.setObjectName("sslabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sslabel)
        self.lcd_Tposition = QtWidgets.QLCDNumber(self.formLayoutWidget_3)
        self.lcd_Tposition.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lcd_Tposition.setDigitCount(6)
        self.lcd_Tposition.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Tposition.setProperty("value", 100000.0)
        self.lcd_Tposition.setObjectName("lcd_Tposition")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lcd_Tposition)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border: none;")
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lcd_Tlength = QtWidgets.QLCDNumber(self.formLayoutWidget_3)
        self.lcd_Tlength.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lcd_Tlength.setDigitCount(6)
        self.lcd_Tlength.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Tlength.setObjectName("lcd_Tlength")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lcd_Tlength)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border: none;")
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lcd_Tstep = QtWidgets.QLCDNumber(self.formLayoutWidget_3)
        self.lcd_Tstep.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lcd_Tstep.setDigitCount(6)
        self.lcd_Tstep.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Tstep.setObjectName("lcd_Tstep")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcd_Tstep)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border: none;")
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lcd_Tslope = QtWidgets.QLCDNumber(self.formLayoutWidget_3)
        self.lcd_Tslope.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lcd_Tslope.setDigitCount(5)
        self.lcd_Tslope.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Tslope.setObjectName("lcd_Tslope")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lcd_Tslope)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pj_p = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.pj_p.setEnabled(False)
        self.pj_p.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pj_p.setCheckable(True)
        self.pj_p.setChecked(True)
        self.pj_p.setObjectName("pj_p")
        self.horizontalLayout_2.addWidget(self.pj_p)
        self.pj_j = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.pj_j.setEnabled(False)
        self.pj_j.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pj_j.setObjectName("pj_j")
        self.horizontalLayout_2.addWidget(self.pj_j)
        self.formLayout_3.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.sslabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.sslabel_2.setFont(font)
        self.sslabel_2.setStyleSheet("border: none;")
        self.sslabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.sslabel_2.setObjectName("sslabel_2")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sslabel_2)
        self.fil_io = QtWidgets.QProgressBar(self.formLayoutWidget_3)
        self.fil_io.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fil_io.setMaximum(1)
        self.fil_io.setProperty("value", 1)
        self.fil_io.setTextVisible(False)
        self.fil_io.setObjectName("fil_io")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fil_io)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("border: none;")
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.verticalLayout_3.addWidget(self.splitter_3)
        self.splitter_2 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border: none;")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lcd_N = QtWidgets.QLCDNumber(self.formLayoutWidget_2)
        self.lcd_N.setDigitCount(3)
        self.lcd_N.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_N.setObjectName("lcd_N")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lcd_N)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border: none;")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lcd_Np = QtWidgets.QLCDNumber(self.formLayoutWidget_2)
        self.lcd_Np.setDigitCount(3)
        self.lcd_Np.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Np.setObjectName("lcd_Np")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lcd_Np)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: none;")
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lcd_Nj = QtWidgets.QLCDNumber(self.formLayoutWidget_2)
        self.lcd_Nj.setDigitCount(3)
        self.lcd_Nj.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Nj.setObjectName("lcd_Nj")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcd_Nj)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border: none;")
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lcd_Nblue = QtWidgets.QLCDNumber(self.formLayoutWidget_2)
        self.lcd_Nblue.setDigitCount(3)
        self.lcd_Nblue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Nblue.setObjectName("lcd_Nblue")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lcd_Nblue)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bAddFile = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bAddFile.setObjectName("bAddFile")
        self.verticalLayout.addWidget(self.bAddFile)
        self.bAddFiles = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bAddFiles.setObjectName("bAddFiles")
        self.verticalLayout.addWidget(self.bAddFiles)
        self.bAddDir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bAddDir.setObjectName("bAddDir")
        self.verticalLayout.addWidget(self.bAddDir)
        self.bReset = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bReset.setObjectName("bReset")
        self.verticalLayout.addWidget(self.bReset)
        self.bDoSave = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bDoSave.setObjectName("bDoSave")
        self.verticalLayout.addWidget(self.bDoSave)
        self.mainlist = QtWidgets.QListWidget(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.mainlist.setFont(font)
        self.mainlist.setObjectName("mainlist")
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.horizontalLayout_4.addWidget(self.splitter_4)
        facewindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(facewindow)
        QtCore.QMetaObject.connectSlotsByName(facewindow)

    def retranslateUi(self, facewindow):
        _translate = QtCore.QCoreApplication.translate
        facewindow.setWindowTitle(_translate("facewindow", "MainWindow"))
        self.radio_deriv.setText(_translate("facewindow", "Derivative"))
        self.radio_view.setText(_translate("facewindow", "Curve"))
        self.radio_smooth.setText(_translate("facewindow", "Smooth"))
        self.labDetails.setText(_translate("facewindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">xxx</p></body></html>"))
        self.labFilename.setText(_translate("facewindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">FILENAME</span></p></body></html>"))
        self.label.setText(_translate("facewindow", "Thresh (std)"))
        self.label_2.setText(_translate("facewindow", "MinLen [nm]"))
        self.label_3.setText(_translate("facewindow", "Window"))
        self.label_4.setText(_translate("facewindow", "Slope (°)"))
        self.label_5.setText(_translate("facewindow", "Zdist [nm]"))
        self.label_6.setText(_translate("facewindow", "LastTH [pN]"))
        self.label_7.setText(_translate("facewindow", "TraitsOrder"))
        self.label_12.setText(_translate("facewindow", "Scope"))
        self.cscope.setText(_translate("facewindow", "General"))
        self.sslabel.setText(_translate("facewindow", "Position"))
        self.label_14.setText(_translate("facewindow", "Length"))
        self.label_15.setText(_translate("facewindow", "Step size"))
        self.label_16.setText(_translate("facewindow", "Slope"))
        self.pj_p.setText(_translate("facewindow", "P"))
        self.pj_j.setText(_translate("facewindow", "J"))
        self.sslabel_2.setText(_translate("facewindow", "Accept"))
        self.label_17.setText(_translate("facewindow", "Type"))
        self.label_8.setText(_translate("facewindow", "N"))
        self.label_9.setText(_translate("facewindow", "N-plateaux"))
        self.label_10.setText(_translate("facewindow", "N-jumps"))
        self.label_11.setText(_translate("facewindow", "N-out"))
        self.bAddFile.setText(_translate("facewindow", "Load one file"))
        self.bAddFiles.setText(_translate("facewindow", "Load Files"))
        self.bAddDir.setText(_translate("facewindow", "Load DIR"))
        self.bReset.setText(_translate("facewindow", "Reset"))
        self.bDoSave.setText(_translate("facewindow", "Do stats and save"))

from pyqtgraph import PlotWidget
