# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\Il mio Drive\Papers\SCFS\SingleCellForceSpectroscopy\canale_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_facewindow(object):
    def setupUi(self, facewindow):
        facewindow.setObjectName("facewindow")
        facewindow.resize(1253, 854)
        facewindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        facewindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../git/SiMPlE/smfsmanager/D_mica.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        facewindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(facewindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.grafo = PlotWidget(self.splitter)
        self.grafo.setMinimumSize(QtCore.QSize(200, 200))
        self.grafo.setToolTip("")
        self.grafo.setStatusTip("")
        self.grafo.setWhatsThis("")
        self.grafo.setObjectName("grafo")
        self.stat = PlotWidget(self.splitter)
        self.stat.setMinimumSize(QtCore.QSize(100, 100))
        self.stat.setObjectName("stat")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radio_area = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radio_area.setFont(font)
        self.radio_area.setObjectName("radio_area")
        self.verticalLayout_4.addWidget(self.radio_area)
        self.radio_deriv = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radio_deriv.setFont(font)
        self.radio_deriv.setObjectName("radio_deriv")
        self.verticalLayout_4.addWidget(self.radio_deriv)
        self.radio_view = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radio_view.setFont(font)
        self.radio_view.setChecked(True)
        self.radio_view.setObjectName("radio_view")
        self.verticalLayout_4.addWidget(self.radio_view)
        self.radio_smooth = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radio_smooth.setFont(font)
        self.radio_smooth.setObjectName("radio_smooth")
        self.verticalLayout_4.addWidget(self.radio_smooth)
        self.radio_traits = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radio_traits.setFont(font)
        self.radio_traits.setObjectName("radio_traits")
        self.verticalLayout_4.addWidget(self.radio_traits)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.cvTree = QtWidgets.QListView(self.layoutWidget)
        self.cvTree.setObjectName("cvTree")
        self.verticalLayout_7.addWidget(self.cvTree)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bAddFile = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bAddFile.setFont(font)
        self.bAddFile.setObjectName("bAddFile")
        self.verticalLayout.addWidget(self.bAddFile)
        self.bAddFiles = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bAddFiles.setFont(font)
        self.bAddFiles.setObjectName("bAddFiles")
        self.verticalLayout.addWidget(self.bAddFiles)
        self.bAddDir = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bAddDir.setFont(font)
        self.bAddDir.setObjectName("bAddDir")
        self.verticalLayout.addWidget(self.bAddDir)
        self.bReset = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bReset.setFont(font)
        self.bReset.setObjectName("bReset")
        self.verticalLayout.addWidget(self.bReset)
        self.bDoSave = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bDoSave.setFont(font)
        self.bDoSave.setObjectName("bDoSave")
        self.verticalLayout.addWidget(self.bDoSave)
        self.famGroup = QtWidgets.QGroupBox(self.groupBox_5)
        self.famGroup.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.famGroup.setFont(font)
        self.famGroup.setCheckable(True)
        self.famGroup.setChecked(False)
        self.famGroup.setObjectName("famGroup")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.famGroup)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.bAddFamily = QtWidgets.QPushButton(self.famGroup)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bAddFamily.setFont(font)
        self.bAddFamily.setObjectName("bAddFamily")
        self.verticalLayout_11.addWidget(self.bAddFamily)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_24 = QtWidgets.QLabel(self.famGroup)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.cNumFam = QtWidgets.QLabel(self.famGroup)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.cNumFam.setFont(font)
        self.cNumFam.setStyleSheet("font-weight: bold;")
        self.cNumFam.setAlignment(QtCore.Qt.AlignCenter)
        self.cNumFam.setObjectName("cNumFam")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cNumFam)
        self.label_25 = QtWidgets.QLabel(self.famGroup)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.cFamilyLoad = QtWidgets.QSlider(self.famGroup)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cFamilyLoad.setFont(font)
        self.cFamilyLoad.setMinimum(1)
        self.cFamilyLoad.setMaximum(1)
        self.cFamilyLoad.setPageStep(2)
        self.cFamilyLoad.setOrientation(QtCore.Qt.Horizontal)
        self.cFamilyLoad.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.cFamilyLoad.setTickInterval(1)
        self.cFamilyLoad.setObjectName("cFamilyLoad")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cFamilyLoad)
        self.verticalLayout_11.addLayout(self.formLayout_4)
        self.verticalLayout.addWidget(self.famGroup)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.s_mth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.s_mth.setFont(font)
        self.s_mth.setMinimum(-100000.0)
        self.s_mth.setMaximum(100000.0)
        self.s_mth.setProperty("value", 2.0)
        self.s_mth.setObjectName("s_mth")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s_mth)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.s_vth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.s_vth.setFont(font)
        self.s_vth.setMinimum(-100000.0)
        self.s_vth.setMaximum(100000.0)
        self.s_vth.setProperty("value", 10.0)
        self.s_vth.setObjectName("s_vth")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s_vth)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: none;")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sg_fw = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sg_fw.setFont(font)
        self.sg_fw.setMinimum(-100000.0)
        self.sg_fw.setMaximum(100000.0)
        self.sg_fw.setProperty("value", 10.0)
        self.sg_fw.setObjectName("sg_fw")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sg_fw)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: none;")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.sg_mm = QtWidgets.QSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sg_mm.setFont(font)
        self.sg_mm.setMaximum(180)
        self.sg_mm.setProperty("value", 10)
        self.sg_mm.setObjectName("sg_mm")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sg_mm)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: none;")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setLineWidth(1)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.plath = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.plath.setFont(font)
        self.plath.setMinimum(-100000.0)
        self.plath.setMaximum(100000.0)
        self.plath.setProperty("value", 30.0)
        self.plath.setObjectName("plath")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.plath)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: none;")
        self.label_6.setLineWidth(1)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lasth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lasth.setFont(font)
        self.lasth.setMaximum(1000.0)
        self.lasth.setProperty("value", 5.0)
        self.lasth.setObjectName("lasth")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lasth)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: none;")
        self.label_7.setLineWidth(1)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.derorder = QtWidgets.QSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.derorder.setFont(font)
        self.derorder.setMaximum(10)
        self.derorder.setProperty("value", 1)
        self.derorder.setObjectName("derorder")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.derorder)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.btn_flatten = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_flatten.setObjectName("btn_flatten")
        self.verticalLayout_5.addWidget(self.btn_flatten)
        self.btn_recalibrate = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_recalibrate.setObjectName("btn_recalibrate")
        self.verticalLayout_5.addWidget(self.btn_recalibrate)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border: none;")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lab_N = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lab_N.setFont(font)
        self.lab_N.setStyleSheet("border: none; font-weight: bold;")
        self.lab_N.setTextFormat(QtCore.Qt.AutoText)
        self.lab_N.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_N.setObjectName("lab_N")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lab_N)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border: none;")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lab_Np = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lab_Np.setFont(font)
        self.lab_Np.setStyleSheet("border: none; font-weight: bold;")
        self.lab_Np.setTextFormat(QtCore.Qt.AutoText)
        self.lab_Np.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Np.setObjectName("lab_Np")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lab_Np)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: none;")
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lab_Nj = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lab_Nj.setFont(font)
        self.lab_Nj.setStyleSheet("border: none; font-weight: bold;")
        self.lab_Nj.setTextFormat(QtCore.Qt.AutoText)
        self.lab_Nj.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Nj.setObjectName("lab_Nj")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lab_Nj)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border: none;")
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lab_Nblue = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lab_Nblue.setFont(font)
        self.lab_Nblue.setStyleSheet("border: none; font-weight: bold;")
        self.lab_Nblue.setTextFormat(QtCore.Qt.AutoText)
        self.lab_Nblue.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Nblue.setObjectName("lab_Nblue")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lab_Nblue)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.reflatten = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.reflatten.setFont(font)
        self.reflatten.setObjectName("reflatten")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.reflatten)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border: none;")
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lcd_Area = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_Area.setFont(font)
        self.lcd_Area.setStyleSheet("font-weight: bold;")
        self.lcd_Area.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_Area.setObjectName("lcd_Area")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lcd_Area)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.lcd_hieght = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_hieght.setFont(font)
        self.lcd_hieght.setStyleSheet("font-weight: bold;")
        self.lcd_hieght.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_hieght.setObjectName("lcd_hieght")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lcd_hieght)
        self.sslabel_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sslabel_4.setFont(font)
        self.sslabel_4.setStyleSheet("border: none;")
        self.sslabel_4.setTextFormat(QtCore.Qt.AutoText)
        self.sslabel_4.setObjectName("sslabel_4")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.sslabel_4)
        self.cnumb = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.cnumb.setFont(font)
        self.cnumb.setStyleSheet("border: none; font-weight: bold;")
        self.cnumb.setTextFormat(QtCore.Qt.AutoText)
        self.cnumb.setAlignment(QtCore.Qt.AlignCenter)
        self.cnumb.setObjectName("cnumb")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.cnumb)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cscope = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cscope.setFont(font)
        self.cscope.setCheckable(True)
        self.cscope.setChecked(False)
        self.cscope.setObjectName("cscope")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.cscope)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.cFamily = QtWidgets.QSlider(self.groupBox_2)
        self.cFamily.setMinimum(1)
        self.cFamily.setMaximum(1)
        self.cFamily.setPageStep(2)
        self.cFamily.setOrientation(QtCore.Qt.Horizontal)
        self.cFamily.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.cFamily.setTickInterval(1)
        self.cFamily.setObjectName("cFamily")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.cFamily)
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.lcd_detX = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcd_detX.setFont(font)
        self.lcd_detX.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_detX.setObjectName("lcd_detX")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lcd_detX)
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.lcd_detF = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcd_detF.setFont(font)
        self.lcd_detF.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_detF.setObjectName("lcd_detF")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lcd_detF)
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.arBlue = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.arBlue.setFont(font)
        self.arBlue.setStyleSheet("background-color:blue; color: white;")
        self.arBlue.setChecked(False)
        self.arBlue.setObjectName("arBlue")
        self.horizontalLayout_11.addWidget(self.arBlue)
        self.arGreen = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.arGreen.setFont(font)
        self.arGreen.setStyleSheet("background-color:green; color: white;")
        self.arGreen.setChecked(True)
        self.arGreen.setObjectName("arGreen")
        self.horizontalLayout_11.addWidget(self.arGreen)
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.lcd_JArea = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcd_JArea.setFont(font)
        self.lcd_JArea.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_JArea.setObjectName("lcd_JArea")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lcd_JArea)
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.str_lim = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.str_lim.setFont(font)
        self.str_lim.setMaximum(99999.0)
        self.str_lim.setSingleStep(2.0)
        self.str_lim.setProperty("value", 20.0)
        self.str_lim.setObjectName("str_lim")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.str_lim)
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.lcd_strA = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcd_strA.setFont(font)
        self.lcd_strA.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_strA.setObjectName("lcd_strA")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lcd_strA)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.btn_popout = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_popout.setObjectName("btn_popout")
        self.verticalLayout_2.addWidget(self.btn_popout)
        self.cbar = QtWidgets.QSlider(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbar.sizePolicy().hasHeightForWidth())
        self.cbar.setSizePolicy(sizePolicy)
        self.cbar.setMinimum(0)
        self.cbar.setMaximum(0)
        self.cbar.setPageStep(10)
        self.cbar.setProperty("value", 0)
        self.cbar.setOrientation(QtCore.Qt.Horizontal)
        self.cbar.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.cbar.setTickInterval(10)
        self.cbar.setObjectName("cbar")
        self.verticalLayout_2.addWidget(self.cbar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.sslabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sslabel.setFont(font)
        self.sslabel.setStyleSheet("border: none;")
        self.sslabel.setTextFormat(QtCore.Qt.AutoText)
        self.sslabel.setObjectName("sslabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sslabel)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border: none;")
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border: none;")
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border: none;")
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("border: none;")
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.sslabel_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sslabel_2.setFont(font)
        self.sslabel_2.setStyleSheet("border: none;")
        self.sslabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.sslabel_2.setObjectName("sslabel_2")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sslabel_2)
        self.sslabel_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sslabel_3.setFont(font)
        self.sslabel_3.setStyleSheet("border: none;")
        self.sslabel_3.setTextFormat(QtCore.Qt.AutoText)
        self.sslabel_3.setObjectName("sslabel_3")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.sslabel_3)
        self.lab_Tslope = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Tslope.sizePolicy().hasHeightForWidth())
        self.lab_Tslope.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lab_Tslope.setFont(font)
        self.lab_Tslope.setStyleSheet("border: none; font-weight: bold;")
        self.lab_Tslope.setTextFormat(QtCore.Qt.AutoText)
        self.lab_Tslope.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Tslope.setObjectName("lab_Tslope")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lab_Tslope)
        self.lab_pj = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_pj.sizePolicy().hasHeightForWidth())
        self.lab_pj.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lab_pj.setFont(font)
        self.lab_pj.setStyleSheet("border: none; font-weight: bold;")
        self.lab_pj.setTextFormat(QtCore.Qt.AutoText)
        self.lab_pj.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_pj.setObjectName("lab_pj")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lab_pj)
        self.fil_io = QtWidgets.QProgressBar(self.groupBox)
        self.fil_io.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fil_io.setMaximum(1)
        self.fil_io.setProperty("value", 1)
        self.fil_io.setTextVisible(False)
        self.fil_io.setObjectName("fil_io")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fil_io)
        self.lab_Tlength = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Tlength.sizePolicy().hasHeightForWidth())
        self.lab_Tlength.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lab_Tlength.setFont(font)
        self.lab_Tlength.setStyleSheet("border: none; font-weight: bold;")
        self.lab_Tlength.setTextFormat(QtCore.Qt.AutoText)
        self.lab_Tlength.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Tlength.setObjectName("lab_Tlength")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lab_Tlength)
        self.pjnumb = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pjnumb.sizePolicy().hasHeightForWidth())
        self.pjnumb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pjnumb.setFont(font)
        self.pjnumb.setStyleSheet("border: none; font-weight: bold;")
        self.pjnumb.setTextFormat(QtCore.Qt.AutoText)
        self.pjnumb.setAlignment(QtCore.Qt.AlignCenter)
        self.pjnumb.setObjectName("pjnumb")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pjnumb)
        self.lab_Tposition = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Tposition.sizePolicy().hasHeightForWidth())
        self.lab_Tposition.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lab_Tposition.setFont(font)
        self.lab_Tposition.setStyleSheet("border: none; font-weight: bold;")
        self.lab_Tposition.setTextFormat(QtCore.Qt.AutoText)
        self.lab_Tposition.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Tposition.setObjectName("lab_Tposition")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lab_Tposition)
        self.lab_Tstep = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Tstep.sizePolicy().hasHeightForWidth())
        self.lab_Tstep.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lab_Tstep.setFont(font)
        self.lab_Tstep.setStyleSheet("border: none; font-weight: bold;")
        self.lab_Tstep.setTextFormat(QtCore.Qt.AutoText)
        self.lab_Tstep.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Tstep.setObjectName("lab_Tstep")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lab_Tstep)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.pjbar = QtWidgets.QSlider(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pjbar.sizePolicy().hasHeightForWidth())
        self.pjbar.setSizePolicy(sizePolicy)
        self.pjbar.setMinimum(0)
        self.pjbar.setMaximum(0)
        self.pjbar.setPageStep(5)
        self.pjbar.setProperty("value", 0)
        self.pjbar.setOrientation(QtCore.Qt.Horizontal)
        self.pjbar.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.pjbar.setTickInterval(1)
        self.pjbar.setObjectName("pjbar")
        self.verticalLayout_3.addWidget(self.pjbar)
        spacerItem4 = QtWidgets.QSpacerItem(10, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.groupBox_6 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.whichStat = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whichStat.sizePolicy().hasHeightForWidth())
        self.whichStat.setSizePolicy(sizePolicy)
        self.whichStat.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.whichStat.setFont(font)
        self.whichStat.setObjectName("whichStat")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.whichStat.addItem("")
        self.verticalLayout_9.addWidget(self.whichStat)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plotStat = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.plotStat.setFont(font)
        self.plotStat.setObjectName("plotStat")
        self.horizontalLayout_2.addWidget(self.plotStat)
        self.redoStat = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.redoStat.setFont(font)
        self.redoStat.setObjectName("redoStat")
        self.horizontalLayout_2.addWidget(self.redoStat)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.separateFamilies = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.separateFamilies.setFont(font)
        self.separateFamilies.setChecked(True)
        self.separateFamilies.setObjectName("separateFamilies")
        self.horizontalLayout_3.addWidget(self.separateFamilies)
        self.fit_gauss = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit_gauss.setFont(font)
        self.fit_gauss.setChecked(True)
        self.fit_gauss.setObjectName("fit_gauss")
        self.horizontalLayout_3.addWidget(self.fit_gauss)
        self.fit_decay = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit_decay.setFont(font)
        self.fit_decay.setObjectName("fit_decay")
        self.horizontalLayout_3.addWidget(self.fit_decay)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.filter_empty = QtWidgets.QGroupBox(self.groupBox_6)
        self.filter_empty.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_empty.sizePolicy().hasHeightForWidth())
        self.filter_empty.setSizePolicy(sizePolicy)
        self.filter_empty.setFlat(False)
        self.filter_empty.setCheckable(True)
        self.filter_empty.setChecked(False)
        self.filter_empty.setObjectName("filter_empty")
        self.formLayout_5 = QtWidgets.QFormLayout(self.filter_empty)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_33 = QtWidgets.QLabel(self.filter_empty)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.minJump = QtWidgets.QDoubleSpinBox(self.filter_empty)
        self.minJump.setMaximum(100000.0)
        self.minJump.setSingleStep(100.0)
        self.minJump.setProperty("value", 1000.0)
        self.minJump.setObjectName("minJump")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.minJump)
        self.verticalLayout_9.addWidget(self.filter_empty)
        self.lim_custom = QtWidgets.QGroupBox(self.groupBox_6)
        self.lim_custom.setCheckable(True)
        self.lim_custom.setChecked(False)
        self.lim_custom.setObjectName("lim_custom")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.lim_custom)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_27 = QtWidgets.QLabel(self.lim_custom)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_8.addWidget(self.label_27)
        self.lim_bins = QtWidgets.QSpinBox(self.lim_custom)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lim_bins.setFont(font)
        self.lim_bins.setMinimum(0)
        self.lim_bins.setMaximum(1000000)
        self.lim_bins.setProperty("value", 10)
        self.lim_bins.setObjectName("lim_bins")
        self.horizontalLayout_8.addWidget(self.lim_bins)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lim_min_range = QtWidgets.QSpinBox(self.lim_custom)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lim_min_range.setFont(font)
        self.lim_min_range.setMinimum(-20000)
        self.lim_min_range.setMaximum(20000)
        self.lim_min_range.setProperty("value", 0)
        self.lim_min_range.setObjectName("lim_min_range")
        self.horizontalLayout_7.addWidget(self.lim_min_range)
        self.label_26 = QtWidgets.QLabel(self.lim_custom)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_7.addWidget(self.label_26)
        self.lim_max_range = QtWidgets.QSpinBox(self.lim_custom)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lim_max_range.setFont(font)
        self.lim_max_range.setMinimum(-20000)
        self.lim_max_range.setMaximum(20000)
        self.lim_max_range.setProperty("value", 0)
        self.lim_max_range.setObjectName("lim_max_range")
        self.horizontalLayout_7.addWidget(self.lim_max_range)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.verticalLayout_9.addWidget(self.lim_custom)
        self.filters_group = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filters_group.sizePolicy().hasHeightForWidth())
        self.filters_group.setSizePolicy(sizePolicy)
        self.filters_group.setCheckable(True)
        self.filters_group.setChecked(False)
        self.filters_group.setObjectName("filters_group")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.filters_group)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lim_min_detach = QtWidgets.QSpinBox(self.filters_group)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lim_min_detach.setFont(font)
        self.lim_min_detach.setMinimum(-99999)
        self.lim_min_detach.setMaximum(99999)
        self.lim_min_detach.setProperty("value", 0)
        self.lim_min_detach.setObjectName("lim_min_detach")
        self.horizontalLayout_9.addWidget(self.lim_min_detach)
        self.label_28 = QtWidgets.QLabel(self.filters_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_9.addWidget(self.label_28)
        self.lim_max_detach = QtWidgets.QSpinBox(self.filters_group)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lim_max_detach.setFont(font)
        self.lim_max_detach.setMinimum(-99999)
        self.lim_max_detach.setMaximum(99999)
        self.lim_max_detach.setProperty("value", 2000)
        self.lim_max_detach.setObjectName("lim_max_detach")
        self.horizontalLayout_9.addWidget(self.lim_max_detach)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lim_min_ntraits = QtWidgets.QSpinBox(self.filters_group)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lim_min_ntraits.setFont(font)
        self.lim_min_ntraits.setMinimum(1)
        self.lim_min_ntraits.setMaximum(99)
        self.lim_min_ntraits.setProperty("value", 1)
        self.lim_min_ntraits.setObjectName("lim_min_ntraits")
        self.horizontalLayout_4.addWidget(self.lim_min_ntraits)
        self.label_19 = QtWidgets.QLabel(self.filters_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.lim_max_ntraits = QtWidgets.QSpinBox(self.filters_group)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lim_max_ntraits.setFont(font)
        self.lim_max_ntraits.setMinimum(1)
        self.lim_max_ntraits.setMaximum(999)
        self.lim_max_ntraits.setProperty("value", 999)
        self.lim_max_ntraits.setObjectName("lim_max_ntraits")
        self.horizontalLayout_4.addWidget(self.lim_max_ntraits)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lim_min_xtrait = QtWidgets.QSpinBox(self.filters_group)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lim_min_xtrait.setFont(font)
        self.lim_min_xtrait.setMinimum(-9999)
        self.lim_min_xtrait.setMaximum(99999)
        self.lim_min_xtrait.setProperty("value", -9999)
        self.lim_min_xtrait.setObjectName("lim_min_xtrait")
        self.horizontalLayout_5.addWidget(self.lim_min_xtrait)
        self.label_20 = QtWidgets.QLabel(self.filters_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.lim_max_xtrait = QtWidgets.QSpinBox(self.filters_group)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lim_max_xtrait.setFont(font)
        self.lim_max_xtrait.setMinimum(-9999)
        self.lim_max_xtrait.setMaximum(99999)
        self.lim_max_xtrait.setProperty("value", 99999)
        self.lim_max_xtrait.setObjectName("lim_max_xtrait")
        self.horizontalLayout_5.addWidget(self.lim_max_xtrait)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lim_min_length = QtWidgets.QSpinBox(self.filters_group)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lim_min_length.setFont(font)
        self.lim_min_length.setMaximum(99999)
        self.lim_min_length.setProperty("value", 0)
        self.lim_min_length.setObjectName("lim_min_length")
        self.horizontalLayout_6.addWidget(self.lim_min_length)
        self.label_21 = QtWidgets.QLabel(self.filters_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_6.addWidget(self.label_21)
        self.lim_max_length = QtWidgets.QSpinBox(self.filters_group)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lim_max_length.setFont(font)
        self.lim_max_length.setMaximum(99999)
        self.lim_max_length.setProperty("value", 99999)
        self.lim_max_length.setObjectName("lim_max_length")
        self.horizontalLayout_6.addWidget(self.lim_max_length)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lim_isJump = QtWidgets.QCheckBox(self.filters_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lim_isJump.setFont(font)
        self.lim_isJump.setChecked(True)
        self.lim_isJump.setObjectName("lim_isJump")
        self.horizontalLayout_10.addWidget(self.lim_isJump)
        self.lim_isPlat = QtWidgets.QCheckBox(self.filters_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lim_isPlat.setFont(font)
        self.lim_isPlat.setChecked(True)
        self.lim_isPlat.setObjectName("lim_isPlat")
        self.horizontalLayout_10.addWidget(self.lim_isPlat)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.verticalLayout_9.addWidget(self.filters_group)
        spacerItem5 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem5)
        self.horizontalLayout.addWidget(self.groupBox_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_8.addWidget(self.splitter_2)
        facewindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(facewindow)
        self.statusBar.setObjectName("statusBar")
        facewindow.setStatusBar(self.statusBar)

        self.retranslateUi(facewindow)
        QtCore.QMetaObject.connectSlotsByName(facewindow)

    def retranslateUi(self, facewindow):
        _translate = QtCore.QCoreApplication.translate
        facewindow.setWindowTitle(_translate("facewindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("facewindow", "View"))
        self.radio_area.setText(_translate("facewindow", "Area"))
        self.radio_deriv.setText(_translate("facewindow", "Derivative"))
        self.radio_view.setText(_translate("facewindow", "Curve"))
        self.radio_smooth.setText(_translate("facewindow", "Smooth"))
        self.radio_traits.setText(_translate("facewindow", "Traits"))
        self.groupBox_5.setTitle(_translate("facewindow", "Actions"))
        self.bAddFile.setText(_translate("facewindow", "Load one file"))
        self.bAddFiles.setText(_translate("facewindow", "Load Files"))
        self.bAddDir.setText(_translate("facewindow", "Load DIR"))
        self.bReset.setText(_translate("facewindow", "Reset"))
        self.bDoSave.setText(_translate("facewindow", "Do stats and save"))
        self.famGroup.setTitle(_translate("facewindow", "Families"))
        self.bAddFamily.setText(_translate("facewindow", "ADD"))
        self.label_24.setText(_translate("facewindow", "Families"))
        self.cNumFam.setText(_translate("facewindow", "1"))
        self.label_25.setText(_translate("facewindow", "Family"))
        self.groupBox_3.setTitle(_translate("facewindow", "Segmentation"))
        self.label.setText(_translate("facewindow", "Thresh (std)"))
        self.label_2.setText(_translate("facewindow", "MinLen [nm]"))
        self.label_3.setText(_translate("facewindow", "Window"))
        self.label_4.setText(_translate("facewindow", "Slope (°)"))
        self.label_5.setText(_translate("facewindow", "Zdist [nm]"))
        self.label_6.setText(_translate("facewindow", "LastTH [pN]"))
        self.label_7.setText(_translate("facewindow", "TraitsOrder"))
        self.btn_flatten.setText(_translate("facewindow", "Flatten"))
        self.btn_recalibrate.setText(_translate("facewindow", "Recalibrate"))
        self.groupBox_2.setTitle(_translate("facewindow", "Curve"))
        self.label_8.setText(_translate("facewindow", "N-segments"))
        self.lab_N.setText(_translate("facewindow", "0"))
        self.label_9.setText(_translate("facewindow", "N-plateaux"))
        self.lab_Np.setText(_translate("facewindow", "0"))
        self.label_10.setText(_translate("facewindow", "N-jumps"))
        self.lab_Nj.setText(_translate("facewindow", "0"))
        self.label_11.setText(_translate("facewindow", "N-out"))
        self.lab_Nblue.setText(_translate("facewindow", "0"))
        self.label_18.setText(_translate("facewindow", "Area method"))
        self.reflatten.setText(_translate("facewindow", "Reflatten"))
        self.label_13.setText(_translate("facewindow", "Area"))
        self.lcd_Area.setText(_translate("facewindow", "0.00 zJ"))
        self.label_22.setText(_translate("facewindow", "Height"))
        self.lcd_hieght.setText(_translate("facewindow", "0 nm"))
        self.sslabel_4.setText(_translate("facewindow", "Number"))
        self.cnumb.setText(_translate("facewindow", "1"))
        self.label_12.setText(_translate("facewindow", "Scope"))
        self.cscope.setText(_translate("facewindow", "General"))
        self.label_23.setText(_translate("facewindow", "Family"))
        self.label_29.setText(_translate("facewindow", "Detach X"))
        self.lcd_detX.setText(_translate("facewindow", "0 nm"))
        self.label_30.setText(_translate("facewindow", "Detach F"))
        self.lcd_detF.setText(_translate("facewindow", "0 pN"))
        self.label_31.setText(_translate("facewindow", "J-Area end"))
        self.arBlue.setText(_translate("facewindow", "B"))
        self.arGreen.setText(_translate("facewindow", "G"))
        self.label_32.setText(_translate("facewindow", "Jump area"))
        self.lcd_JArea.setText(_translate("facewindow", "0.00 zJ"))
        self.label_34.setText(_translate("facewindow", "Stretch lim"))
        self.label_35.setText(_translate("facewindow", "Stretch area"))
        self.lcd_strA.setText(_translate("facewindow", "0.00 zJ"))
        self.btn_popout.setText(_translate("facewindow", "POP OUT"))
        self.groupBox.setTitle(_translate("facewindow", "Segment"))
        self.sslabel.setText(_translate("facewindow", "Position"))
        self.label_14.setText(_translate("facewindow", "Length"))
        self.label_15.setText(_translate("facewindow", "Step size"))
        self.label_16.setText(_translate("facewindow", "Slope"))
        self.label_17.setText(_translate("facewindow", "Type"))
        self.sslabel_2.setText(_translate("facewindow", "Accept"))
        self.sslabel_3.setText(_translate("facewindow", "Number"))
        self.lab_Tslope.setText(_translate("facewindow", "0.00"))
        self.lab_pj.setText(_translate("facewindow", "Plateaux"))
        self.lab_Tlength.setText(_translate("facewindow", "0.00"))
        self.pjnumb.setText(_translate("facewindow", "1"))
        self.lab_Tposition.setText(_translate("facewindow", "0.00"))
        self.lab_Tstep.setText(_translate("facewindow", "0.00"))
        self.groupBox_6.setTitle(_translate("facewindow", "Statistics"))
        self.whichStat.setItemText(0, _translate("facewindow", "ADHESION [pN]"))
        self.whichStat.setItemText(1, _translate("facewindow", "Stretch AREA [fJ]"))
        self.whichStat.setItemText(2, _translate("facewindow", "DETACH-X [nm]"))
        self.whichStat.setItemText(3, _translate("facewindow", "DETACH-F [pN]"))
        self.whichStat.setItemText(4, _translate("facewindow", "AREA [fJ]"))
        self.whichStat.setItemText(5, _translate("facewindow", "Jump SLOPE [pN/nm]"))
        self.whichStat.setItemText(6, _translate("facewindow", "NTRAITS"))
        self.whichStat.setItemText(7, _translate("facewindow", "NJUMPS"))
        self.whichStat.setItemText(8, _translate("facewindow", "NPLATEAUX"))
        self.whichStat.setItemText(9, _translate("facewindow", "Max Step [pN]"))
        self.whichStat.setItemText(10, _translate("facewindow", "Segments LENGTH [nm]"))
        self.whichStat.setItemText(11, _translate("facewindow", "Segments POSITION [nm]"))
        self.whichStat.setItemText(12, _translate("facewindow", "Segments STEP [pN]"))
        self.whichStat.setItemText(13, _translate("facewindow", "Segments SLOPE [pN/nm]"))
        self.plotStat.setText(_translate("facewindow", "Plot stats"))
        self.redoStat.setText(_translate("facewindow", "Redo Stats"))
        self.separateFamilies.setText(_translate("facewindow", "Families"))
        self.fit_gauss.setToolTip(_translate("facewindow", "ciao"))
        self.fit_gauss.setText(_translate("facewindow", "Gauss Fit"))
        self.fit_decay.setText(_translate("facewindow", "Decay Fit"))
        self.filter_empty.setTitle(_translate("facewindow", "Filter empty"))
        self.label_33.setText(_translate("facewindow", "Min jump [pN]"))
        self.lim_custom.setTitle(_translate("facewindow", "Customize"))
        self.label_27.setToolTip(_translate("facewindow", "Number of GOOD traits to be filtered"))
        self.label_27.setText(_translate("facewindow", "Bins"))
        self.label_26.setToolTip(_translate("facewindow", "Number of GOOD traits to be filtered"))
        self.label_26.setText(_translate("facewindow", "< Value <"))
        self.filters_group.setTitle(_translate("facewindow", "Filters"))
        self.label_28.setToolTip(_translate("facewindow", "Number of GOOD traits to be filtered"))
        self.label_28.setText(_translate("facewindow", "< xDetach <"))
        self.label_19.setToolTip(_translate("facewindow", "Number of GOOD traits to be filtered"))
        self.label_19.setText(_translate("facewindow", "< NTraits <"))
        self.label_20.setToolTip(_translate("facewindow", "Position of the first point of the trait, for filtering"))
        self.label_20.setText(_translate("facewindow", "< xTrait <"))
        self.label_21.setToolTip(_translate("facewindow", "Lenght of the trait"))
        self.label_21.setText(_translate("facewindow", "< Length <"))
        self.lim_isJump.setText(_translate("facewindow", "Jump"))
        self.lim_isPlat.setText(_translate("facewindow", "Plateaux"))

from pyqtgraph import PlotWidget
